package com.pelonot.domain.identity

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * PLAN 20.2.1, 20.2.2, 20.2.3, 20.6.1, 20.6.3.
 *
 * The cases worth pinning are the ones about **absence and about values this
 * build does not recognise**, because both reach the first screen anybody sees
 * and neither is exercised by the happy path.
 */
class AvatarTest {

    @Test
    fun `a stored choice round-trips`() {
        val chosen = Avatar(AvatarPaint.Rose, AvatarFace.Lark)
        assertEquals(chosen, Avatar.parse(chosen.store(), localUserId = 1))
    }

    @Test
    fun `a colour with no face round-trips, and the face stays absent`() {
        val chosen = Avatar(AvatarPaint.Sky)
        assertEquals("sky", chosen.store())
        val read = Avatar.parse("sky", localUserId = 1)
        assertEquals(AvatarPaint.Sky, read.paint)
        // Null means *the rider's own initial*, which is a different thing from
        // any face in the set and must not be filled in with one.
        assertNull(read.face)
    }

    @Test
    fun `null means never chosen, and the id answers`() {
        assertEquals(Avatar.defaultFor(3), Avatar.parse(null, localUserId = 3))
        assertEquals(Avatar.defaultFor(3), Avatar.parse("", localUserId = 3))
        assertEquals(Avatar.defaultFor(3), Avatar.parse("   ", localUserId = 3))
    }

    @Test
    fun `the default is stable for a profile and spreads across a household`() {
        assertEquals(Avatar.defaultFor(7), Avatar.defaultFor(7))
        // A bike with four riders on it gets four different faces without
        // anybody being asked a question (20.2.3).
        val household = (1..4).map { Avatar.defaultFor(it).paint }
        assertEquals(4, household.toSet().size)
    }

    @Test
    fun `the default never wears a face`() {
        // A face is a thing the rider chose. Handing one out would make
        // "chosen" and "not chosen" indistinguishable on screen.
        (0..20).forEach { assertNull(Avatar.defaultFor(it).face) }
    }

    @Test
    fun `an unrecognised colour falls back rather than throwing`() {
        // What a newer build's value looks like to this one. The first screen
        // anybody sees must not crash on it.
        assertEquals(Avatar.defaultFor(2), Avatar.parse("photo:me.webp", localUserId = 2))
        assertEquals(Avatar.defaultFor(2), Avatar.parse("c3", localUserId = 2))
    }

    @Test
    fun `a known colour with an unknown face keeps the colour`() {
        val read = Avatar.parse("leaf:unicorn", localUserId = 5)
        assertEquals(AvatarPaint.Leaf, read.paint)
        assertNull(read.face)
    }

    @Test
    fun `a retired icon mark degrades to the colour and the initial`() {
        // 20.6.3. The six `AvatarMark` ids are gone, and the one profile on the
        // test device that chose `rose:bolt` must become rose with an initial
        // rather than a crash or a blank disc. Nothing is migrated: the column
        // keeps the string the rider wrote.
        listOf("bolt", "mountain", "paw", "note", "rocket", "coffee").forEach { retired ->
            val read = Avatar.parse("rose:$retired", localUserId = 5)
            assertEquals(AvatarPaint.Rose, read.paint)
            assertNull(read.face)
        }
    }

    @Test
    fun `a negative or zero id still resolves`() {
        // `localUserId` is autogenerated and positive in practice, so this is
        // the modulus being made safe rather than the input being trusted.
        assertEquals(AvatarPaint.entries.first(), Avatar.defaultFor(0).paint)
        Avatar.defaultFor(-1)
        Avatar.defaultFor(Int.MIN_VALUE)
    }

    @Test
    fun `ids are unique and stable words, because the column stores them`() {
        assertEquals(AvatarPaint.entries.size, AvatarPaint.entries.map { it.id }.toSet().size)
        assertEquals(AvatarFace.entries.size, AvatarFace.entries.map { it.id }.toSet().size)
        // Renaming one silently re-colours every rider who chose it, so the
        // words are pinned here as well as in the KDoc.
        assertEquals(
            listOf("periwinkle", "turquoise", "leaf", "rose", "lilac", "sky", "sand", "slate"),
            AvatarPaint.entries.map { it.id }
        )
        // The face ids are the seeds `avatars/fetch.sh` rendered from, so they
        // are pinned in three places on purpose: here, the script, and the
        // `res/drawable-nodpi/avatar_*.png` filenames.
        assertEquals(
            listOf(
                "ash", "bay", "cove", "dune", "elm", "fern", "glen", "haze", "isle", "kite",
                "lark", "moss", "nova", "opal", "pine", "quill", "reed", "sage", "tide", "vale"
            ),
            AvatarFace.entries.map { it.id }
        )
    }

    @Test
    fun `a face and no face are different avatars`() {
        assertNotEquals(Avatar(AvatarPaint.Rose), Avatar(AvatarPaint.Rose, AvatarFace.Pine))
    }
}
