package com.pelonot.domain.identity

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * PLAN 20.2.1, 20.2.2, 20.2.3, 20.6.1, 20.6.3.
 *
 * The cases worth pinning are the ones about **absence and about values this
 * build does not recognise**, because both reach the first screen anybody sees
 * and neither is exercised by the happy path.
 */
class AvatarTest {

    @Test
    fun `a stored choice round-trips`() {
        val chosen = Avatar(AvatarPaint.Rose, AvatarFace.Lark)
        assertEquals(chosen, Avatar.parse(chosen.store(), localUserId = 1))
    }

    @Test
    fun `a colour with no face round-trips, and the face stays absent`() {
        val chosen = Avatar(AvatarPaint.Sky)
        assertEquals("sky", chosen.store())
        val read = Avatar.parse("sky", localUserId = 1)
        assertEquals(AvatarPaint.Sky, read.paint)
        // Null means *the rider's own initial*, which is a different thing from
        // any face in the set and must not be filled in with one.
        assertNull(read.face)
    }

    @Test
    fun `null means never chosen, and the id answers`() {
        assertEquals(Avatar.defaultFor(3), Avatar.parse(null, localUserId = 3))
        assertEquals(Avatar.defaultFor(3), Avatar.parse("", localUserId = 3))
        assertEquals(Avatar.defaultFor(3), Avatar.parse("   ", localUserId = 3))
    }

    @Test
    fun `the default is stable for a profile and spreads across a household`() {
        assertEquals(Avatar.defaultFor(7), Avatar.defaultFor(7))
        // A bike with four riders on it gets four different faces without
        // anybody being asked a question (20.2.3).
        val household = (1..4).map { Avatar.defaultFor(it).paint }
        assertEquals(4, household.toSet().size)
    }

    @Test
    fun `the default never wears a face`() {
        // A face is a thing the rider chose. Handing one out would make
        // "chosen" and "not chosen" indistinguishable on screen.
        (0..20).forEach { assertNull(Avatar.defaultFor(it).face) }
    }

    @Test
    fun `an unrecognised colour falls back rather than throwing`() {
        // What a newer build's value looks like to this one. The first screen
        // anybody sees must not crash on it.
        assertEquals(Avatar.defaultFor(2), Avatar.parse("photo:me.webp", localUserId = 2))
        assertEquals(Avatar.defaultFor(2), Avatar.parse("c3", localUserId = 2))
    }

    @Test
    fun `a known colour with an unknown face keeps the colour`() {
        val read = Avatar.parse("leaf:unicorn", localUserId = 5)
        assertEquals(AvatarPaint.Leaf, read.paint)
        assertNull(read.face)
    }

    @Test
    fun `a retired icon mark degrades to the colour and the initial`() {
        // 20.6.3. The six `AvatarMark` ids are gone, and the one profile on the
        // test device that chose `rose:bolt` must become rose with an initial
        // rather than a crash or a blank disc. Nothing is migrated: the column
        // keeps the string the rider wrote.
        listOf("bolt", "mountain", "paw", "note", "rocket", "coffee").forEach { retired ->
            val read = Avatar.parse("rose:$retired", localUserId = 5)
            assertEquals(AvatarPaint.Rose, read.paint)
            assertNull(read.face)
        }
    }

    @Test
    fun `a negative or zero id still resolves`() {
        // `localUserId` is autogenerated and positive in practice, so this is
        // the modulus being made safe rather than the input being trusted.
        assertEquals(AvatarPaint.entries.first(), Avatar.defaultFor(0).paint)
        Avatar.defaultFor(-1)
        Avatar.defaultFor(Int.MIN_VALUE)
    }

    @Test
    fun `ids are unique and stable words, because the column stores them`() {
        assertEquals(AvatarPaint.entries.size, AvatarPaint.entries.map { it.id }.toSet().size)
        assertEquals(AvatarFace.entries.size, AvatarFace.entries.map { it.id }.toSet().size)
        // Renaming one silently re-colours every rider who chose it, so the
        // words are pinned here as well as in the KDoc.
        assertEquals(
            listOf("periwinkle", "turquoise", "leaf", "rose", "lilac", "sky", "sand", "slate"),
            AvatarPaint.entries.map { it.id }
        )
        // The face ids are the seeds `avatars/fetch.sh` rendered from, so they
        // are pinned in three places on purpose: here, the script, and the
        // `res/drawable-nodpi/avatar_*.png` filenames.
        assertEquals(
            listOf(
                "ash", "bay", "cove", "dune", "elm", "fern", "glen", "haze", "isle", "kite",
                "lark", "moss", "nova", "opal", "pine", "quill", "reed", "sage", "tide", "vale"
            ),
            AvatarFace.entries.map { it.id }
        )
    }

    @Test
    fun `a face and no face are different avatars`() {
        assertNotEquals(Avatar(AvatarPaint.Rose), Avatar(AvatarPaint.Rose, AvatarFace.Pine))
    }

    // ---- The photograph scheme (20.2.4) ----

    @Test
    fun `a photograph round-trips and wins over a face`() {
        val photo = AvatarPhoto.nameFor(localUserId = 2, atEpochMs = 1_700_000_000_000)
        val chosen = Avatar(AvatarPaint.Rose, AvatarFace.Lark, photo)

        // The face is still on the object and deliberately not in the column:
        // a photograph is what the rider chose, and writing both would leave
        // two answers on disk for the app to have to prefer between later.
        assertEquals("photo:avatar-2-1700000000000.jpg", chosen.store())

        val read = Avatar.parse(chosen.store(), localUserId = 2)
        assertEquals(photo, read.photo)
        assertNull(read.face)
    }

    @Test
    fun `a photograph keeps the colour the rider would have had`() {
        // The reason the colour survives beside the photograph at all: the file
        // can be missing — a database imported onto another tablet (12.4.4)
        // names pictures that did not travel — and the disc then falls back to
        // exactly the face of somebody who never chose.
        val stored = "photo:avatar-7-1700000000000.jpg"
        assertEquals(Avatar.defaultFor(7).paint, Avatar.parse(stored, localUserId = 7).paint)
    }

    @Test
    fun `a photograph name this app did not write is not a photograph`() {
        // The fence, and it is the reason `AvatarPhoto.of` exists: this value
        // reaches a `File(directory, name)`, and the column is one this project
        // edits by hand in `sqlite3` constantly.
        listOf(
            "photo:../../databases/pelonot_database",
            "photo:/etc/hosts",
            "photo:avatar-2-1700000000000.jpg.exe",
            "photo:avatar--1.jpg",
            "photo:"
        ).forEach { stored ->
            val read = Avatar.parse(stored, localUserId = 4)
            assertNull("$stored was accepted as a photograph", read.photo)
            // And it degrades the way every unrecognised value does.
            assertEquals(Avatar.defaultFor(4), read)
        }
    }

    @Test
    fun `no colour is named photo, because the prefix would silently win`() {
        // `parse` reads the photograph branch first, so a paint with this id
        // would make every rider who chose it read back as a picture nobody
        // took. Pinned rather than trusted to the eight words above.
        assertNull(AvatarPaint.entries.firstOrNull { it.id == "photo" })
    }
}
