package com.pelonot.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.pelonot.data.local.entity.FtpHistoryEntity
import kotlinx.coroutines.flow.Flow

/**
 * The record of a rider's FTP over time (PLAN 7.9).
 *
 * Append-only by design. There is no update and no delete: an FTP change
 * happened, and a later change does not un-happen it. The one way a row leaves
 * is the profile being deleted, which the foreign key handles.
 */
@Dao
interface FtpHistoryDao {

    /**
     * `@Insert` with no conflict strategy, which is the strict one.
     *
     * Not `@Upsert` and emphatically not `REPLACE` — the primary key is
     * autogenerated, so there is nothing to conflict with, and a REPLACE here
     * would be the fourth instance of the delete-plus-insert defect this
     * project has already had three of.
     */
    @Insert
    suspend fun insert(entry: FtpHistoryEntity): Long

    /** Oldest first, which is the order a trend line is drawn in. */
    @Query(
        """
        SELECT * FROM ftp_history
        WHERE local_user_id = :userId
        ORDER BY changed_at ASC, id ASC
        """
    )
    fun observeForUser(userId: Int): Flow<List<FtpHistoryEntity>>

    @Query(
        """
        SELECT * FROM ftp_history
        WHERE local_user_id = :userId
        ORDER BY changed_at ASC, id ASC
        """
    )
    suspend fun forUser(userId: Int): List<FtpHistoryEntity>

    @Query("SELECT COUNT(*) FROM ftp_history WHERE local_user_id = :userId")
    suspend fun countForUser(userId: Int): Int
}
