#!/usr/bin/env bash
#
# PLAN 19.1.7a — the measurements on STATUS.md, emitted rather than typed.
#
# STATUS.md is *regenerated* rather than maintained (19.1.7), and the sixty-
# fourth sitting found it seven sittings behind: 795 JVM tests where the build
# said 858, and a box count of 618 of 837 against a real 651 of 863. That is the
# condition 19.1.7a set before building this — "do not build it until the file
# has actually gone stale once", for 17.15.2's reason that a generator nobody
# runs is worse than a page somebody rewrites.
#
# **It emits the measurements and never the prose.** What went stale on this
# page has twice been four sentences about what a rider meets, and no script can
# check those; what it *can* make impossible is a number stated wrongly. So the
# figures live between two markers in STATUS.md and nothing else in the file is
# touched.
#
#   tools/status-figures.sh            print the figures
#   tools/status-figures.sh --write    write them into STATUS.md
#   tools/status-figures.sh --check    fail if STATUS.md disagrees (CI)
#
# The JVM test count comes from the build's own results, so `--check` has to run
# *after* `testDebugUnitTest`. A missing results directory is an error rather
# than a zero: silently reporting no tests is exactly the shape of drift this
# exists to stop.

set -euo pipefail

cd "$(dirname "$0")/.."

BEGIN='<!-- figures:begin -->'
END='<!-- figures:end -->'
RESULTS=app/build/test-results/testDebugUnitTest

plan_files=(PLAN.md plan/*.md)

# Indented sub-items count. The plain `^- \[x\]` pattern this page used before
# silently excludes 20.2.4a-f and every other nested box, which is how two
# phases were carried at figures that were wrong in opposite directions
# (PLAN.md's own note, sixty-sixth sitting).
ticked=$(grep -chE '^[[:space:]]*- \[x\]' "${plan_files[@]}" | paste -sd+ - | bc)
total=$(grep -chE '^[[:space:]]*- \[[ x]\]' "${plan_files[@]}" | paste -sd+ - | bc)
percent=$(( ticked * 100 / total ))

if [[ ! -d $RESULTS ]]; then
    echo "no test results at $RESULTS — run ./gradlew testDebugUnitTest first" >&2
    exit 2
fi

sum_attr() {
    grep -rho "$1=\"[0-9]*\"" "$RESULTS"/*.xml | tr -dc '0-9\n' | paste -sd+ - | bc
}

tests=$(sum_attr tests)
failures=$(sum_attr failures)
errors=$(sum_attr errors)

if [[ $failures -ne 0 || $errors -ne 0 ]]; then
    echo "the suite is not green ($failures failures, $errors errors) — fix that first" >&2
    exit 2
fi

figures=$(cat <<EOF
$BEGIN
<!-- Generated by tools/status-figures.sh (19.1.7a). Do not edit by hand. -->

| Measured | |
|---|---|
| JVM tests | **$tests**, 0 failures |
| Plan boxes ticked | **$ticked of $total** — $percent% |

*Counted as \`grep -cE '^[[:space:]]*- \[x\]' PLAN.md plan/*.md\`, indented
sub-items included. Read the percentage as an inventory count and never as a
completion estimate — the paragraph at the end of this page says why.*
$END
EOF
)

case "${1:-}" in
    --write)
        python3 - "$figures" <<'PY'
import re, sys
figures = sys.argv[1]
page = open('STATUS.md').read()
begin, end = '<!-- figures:begin -->', '<!-- figures:end -->'
if begin not in page or end not in page:
    sys.exit(f'STATUS.md has no {begin} … {end} region to write into')
head, rest = page.split(begin, 1)
_, tail = rest.split(end, 1)
open('STATUS.md', 'w').write(head + figures + tail)
PY
        echo "STATUS.md figures updated"
        ;;
    --check)
        if ! grep -qF "$BEGIN" STATUS.md; then
            echo "STATUS.md has no figures block — run tools/status-figures.sh --write" >&2
            exit 1
        fi
        current=$(awk -v b="$BEGIN" -v e="$END" '$0==b{p=1} p{print} $0==e{p=0}' STATUS.md)
        if [[ "$current" != "$figures" ]]; then
            echo "STATUS.md's figures have drifted. Expected:" >&2
            echo "$figures" >&2
            echo "--- found: ---" >&2
            echo "$current" >&2
            echo "Run tools/status-figures.sh --write" >&2
            exit 1
        fi
        echo "STATUS.md figures are current: $tests tests, $ticked of $total boxes"
        ;;
    *)
        echo "$figures"
        ;;
esac
